# Generated by Django 5.2.14 on 2026-05-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leases", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("lease_expiry", "Lease Expiry"),
                            ("rent_due", "Rent Due"),
                            ("property_tax", "Property Tax Filing"),
                            ("insurance", "Insurance Renewal"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_date", models.DateField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="leases.lease",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["trigger_date"],
            },
        ),
    ]
