# Generated by Django 5.2.14 on 2026-05-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("plot", "Plot"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "area_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[
                            ("marla", "Marla"),
                            ("kanal", "Kanal"),
                            ("sq_ft", "Square Feet"),
                            ("sq_yd", "Square Yards"),
                        ],
                        default="marla",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rented", "Rented"),
                            ("vacant", "Vacant"),
                            ("under_construction", "Under Construction"),
                            ("for_sale", "For Sale"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("registry", "Registry"),
                            ("tax_receipt", "Tax Receipt"),
                            ("utility", "Utility Connection"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="properties/documents/")),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="properties/photos/")),
                ("taken_on", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pre_tenant", "Pre-tenant condition"),
                            ("current", "Current state"),
                            ("damage", "Damage record"),
                            ("other", "Other"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-taken_on", "-created_at"],
            },
        ),
    ]
