# Generated by Django 5.2.14 on 2026-05-31 06:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "annual_escalation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="Percentage applied each anniversary year (Pakistani norm is ~10%).",
                        max_digits=5,
                    ),
                ),
                (
                    "rent_due_day",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Day of month rent is due (1-28)."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("property",),
                        name="unique_active_lease_per_property",
                    )
                ],
            },
        ),
    ]
