# Generated by Django 5.2.14 on 2026-05-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("due_date", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="leases.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="RentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Cheque #, transaction ID, etc.",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.rentinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on"],
            },
        ),
        migrations.CreateModel(
            name="WithholdingTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deducted_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("certificate_ref", models.CharField(blank=True, max_length=120)),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="payments/wht/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withholding_taxes",
                        to="payments.rentinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "withholding tax entry",
                "verbose_name_plural": "withholding tax entries",
                "ordering": ["-deducted_on"],
            },
        ),
        migrations.AddConstraint(
            model_name="rentinvoice",
            constraint=models.UniqueConstraint(
                fields=("lease", "period_start"), name="unique_invoice_per_lease_period"
            ),
        ),
    ]
