# Generated by Django 5.2.14 on 2026-05-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("fbr_notice", "FBR Notice"),
                            ("cantonment_notice", "Cantonment Board Notice"),
                            ("section_7e", "Section 7E Exemption Certificate"),
                            ("nadra", "NADRA Document"),
                            ("correspondence", "Correspondence"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="vault/")),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vault_documents",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-created_at"],
            },
        ),
    ]
